name: Build Android APK

on:
  push:
    branches:
      - main  # Set this to your default branch name, e.g., main or master
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This action is usually fine as it does not depend on Node.js.

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Ensure the Python version you need.



    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install kivy buildozer

    - name: Build APK
      run: |
        source venv/bin/activate
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: ./bin/*.apk
